# Parsing Massey Data

This notebook parses Massey College Football data by conference and year from URLs like this one:  
https://masseyratings.com/scores.php?all=1&format=2&s=587076&sub=10678

That should return the teams in the B1G during 2024; set `format=1` for the games. The code below merges those two data frames into one with the team names and scores. It does so for several years and the power 4/5 conferences. These easiest way to find the query string for conference and year is to navigate from  
https://masseyratings.com/data

Note that the response will be empty, until you provide `all` and `format` values.

In [1]:
import pandas as pd
import time

In [3]:
conferences_by_year = [
    {'conf': 'B1G', 'year': 2025, 'q': 's=627248&sub=10678'},
    {'conf': 'B1G', 'year': 2024, 'q': 's=587076&sub=10678'},
    {'conf': 'ACC', 'year': 2024, 'q': 's=587076&sub=10423'},
    {'conf': 'SEC', 'year': 2024, 'q': 's=587076&sub=14028'},
    {'conf': 'Big12', 'year': 2024, 'q': 's=587076&sub=10686'},

    {'conf': 'ACC', 'year': 2023, 'q': 's=539277&sub=10423'},
    {'conf': 'B1G', 'year': 2023, 'q': 's=539277&sub=10678'},
    {'conf': 'Big12', 'year': 2023, 'q': 's=539277&sub=10686'},
    {'conf': 'SEC', 'year': 2023, 'q': 's=539277&sub=14028'},
    {'conf': 'PAC12', 'year': 2023, 'q': 's=539277&sub=107818'},

    {'conf': 'ACC', 'year': 2022, 'q': 's=384031&sub=10423'},
    {'conf': 'B1G', 'year': 2022, 'q': 's=384031&sub=10678'},
    {'conf': 'Big12', 'year': 2022, 'q': 's=384031&sub=10686'},
    {'conf': 'SEC', 'year': 2022, 'q': 's=384031&sub=14028'},
    {'conf': 'PAC12', 'year': 2022, 'q': 's=384031&sub=107818'},

    {'conf': 'ACC', 'year': 2021, 'q': 's=358435&sub=10423'},
    {'conf': 'B1G', 'year': 2021, 'q': 's=358435&sub=10678'},
    {'conf': 'Big12', 'year': 2021, 'q': 's=358435&sub=10686'},
    {'conf': 'SEC', 'year': 2021, 'q': 's=358435&sub=14028'},
    {'conf': 'PAC12', 'year': 2021, 'q': 's=358435&sub=107818'},

    {'conf': 'ACC', 'year': 2019, 'q': 's=308075&sub=10423'},
    {'conf': 'B1G', 'year': 2019, 'q': 's=308075&sub=10678'},
    {'conf': 'Big12', 'year': 2019, 'q': 's=308075&sub=10686'},
    {'conf': 'SEC', 'year': 2019, 'q': 's=308075&sub=14028'},
    {'conf': 'PAC12', 'year': 2019, 'q': 's=308075&sub=107818'},

    {'conf': 'ACC', 'year': 2018, 'q': 's=300937&sub=10423'},
    {'conf': 'B1G', 'year': 2018, 'q': 's=300937&sub=10678'},
    {'conf': 'Big12', 'year': 2018, 'q': 's=300937&sub=10686'},
    {'conf': 'SEC', 'year': 2018, 'q': 's=300937&sub=14028'},
    {'conf': 'PAC12', 'year': 2018, 'q': 's=300937&sub=107818'},

    {'conf': 'ACC', 'year': 2017, 'q': 's=295489&sub=10423'},
    {'conf': 'B1G', 'year': 2017, 'q': 's=295489&sub=10678'},
    {'conf': 'Big12', 'year': 2017, 'q': 's=295489&sub=10686'},
    {'conf': 'SEC', 'year': 2017, 'q': 's=295489&sub=14028'},
    {'conf': 'PAC12', 'year': 2017, 'q': 's=295489&sub=107818'}
]

In [18]:
len(conferences_by_year)

35

In [4]:
all_games = pd.DataFrame()
for cy in conferences_by_year:
    teams = pd.read_csv(
        f"https://masseyratings.com/scores.php?all=1&format=2&{cy['q']}",
        names = ['massey_id', 'massey_name']
    )
    games = pd.read_csv(
        f"https://masseyratings.com/scores.php?all=1&format=1&{cy['q']}",
        names = ["day","date","team1","home1","score1","team2","home2","score2"],
        parse_dates=['date'], date_format= '%Y%m%d'
    )
    # Add team names and idx (to be used as a matrix index)
    teams['idx'] = teams.index
    reindexed_teams = teams.set_index('massey_id')
    id_to_name_dict = reindexed_teams['massey_name'].to_dict()
    id_to_idx_dict = reindexed_teams['idx'].to_dict()
    games['WTeamName'] = games.team1.apply(lambda t: id_to_name_dict[t].strip())
    games['LTeamName'] = games.team2.apply(lambda t: id_to_name_dict[t].strip())
    # games['team1_idx'] = games.team1.apply(lambda t: id_to_idx_dict[t])
    # games['team2_idx'] = games.team2.apply(lambda t: id_to_idx_dict[t])

    games['WScore'] = games.score1
    games['LScore'] = games.score2
    games['year'] = cy['year']
    games['conf'] = cy['conf']

    all_games = pd.concat(
        [all_games, games[['year', 'conf', 'WTeamName', 'WScore', 'LTeamName', 'LScore']]], 
        ignore_index=True
    )
    time.sleep(1)

In [5]:
all_games

      year   conf   WTeamName  WScore      LTeamName  LScore
0     2025    B1G      Oregon      34   Northwestern      14
1     2025    B1G         USC      33         Purdue      17
2     2025    B1G        Iowa      38        Rutgers      28
3     2025    B1G     Indiana      63       Illinois      10
4     2025    B1G    Michigan      30       Nebraska      27
...    ...    ...         ...     ...            ...     ...
2039  2017  PAC12  Arizona_St      42        Arizona      30
2040  2017  PAC12        Utah      34       Colorado      13
2041  2017  PAC12      Oregon      69      Oregon_St      10
2042  2017  PAC12  Washington      41  Washington_St      14
2043  2017  PAC12         USC      31       Stanford      28

[2044 rows x 6 columns]

In [21]:
all_games.to_csv("cfb_games_by_conf_and_year.csv", index=False)

In [23]:
# Read in Massey's list of teams and ids
teams = pd.read_csv(
    'https://masseyratings.com/scores.php?all=1&format=2&s=627248&sub=10678',
    names = ['massey_id', 'massey_name']
)
games = pd.read_csv(
    # 'https://masseyratings.com/scores.php?s=627248&sub=10678&all=1&mode=3&format=1',
    'https://masseyratings.com/scores.php?all=1&format=1&s=627248&sub=10678',
    names = ["day","date","team1","home1","score1","team2","home2","score2"],
    parse_dates=['date'], date_format= '%Y%m%d'
)

# Add team names and idx (to be used as a matrix index)
teams['idx'] = teams.index
reindexed_teams = teams.set_index('massey_id')
id_to_name_dict = reindexed_teams['massey_name'].to_dict()
id_to_idx_dict = reindexed_teams['idx'].to_dict()
games['WTeamName'] = games.team1.apply(lambda t: id_to_name_dict[t].strip())
games['LTeamName'] = games.team2.apply(lambda t: id_to_name_dict[t].strip())
# games['team1_idx'] = games.team1.apply(lambda t: id_to_idx_dict[t])
# games['team2_idx'] = games.team2.apply(lambda t: id_to_idx_dict[t])

games['WScore'] = games.score1
games['LScore'] = games.score2

just_games = games[['WTeamName', 'WScore', 'LTeamName', 'LScore']]
just_games

       WTeamName  WScore     LTeamName  LScore
0         Oregon      34  Northwestern      14
1            USC      33        Purdue      17
2           Iowa      38       Rutgers      28
3        Indiana      63      Illinois      10
4       Michigan      30      Nebraska      27
5            USC      45   Michigan_St      31
6       Maryland      27     Wisconsin      10
7       Illinois      34           USC      32
8        Indiana      20          Iowa      15
9      Minnesota      31       Rutgers      28
10  Northwestern      17          UCLA      14
11        Oregon      30       Penn_St      24
12       Ohio_St      24    Washington       6
13    Washington      24      Maryland      20
14      Michigan      24     Wisconsin      10
15      Nebraska      38   Michigan_St      27
16       Ohio_St      42     Minnesota       3
17      Illinois      43        Purdue      27
18          UCLA      42       Penn_St      37
19    Washington      38       Rutgers      19
20       Ohio_St      34      Illinois      16
21      Nebraska      34      Maryland      31
22          UCLA      38   Michigan_St      13
23     Minnesota      27        Purdue      20
24       Indiana      30        Oregon      20
25  Northwestern      22       Penn_St      21
26           USC      31      Michigan      13
27          Iowa      37     Wisconsin       0
28     Minnesota      24      Nebraska       6
29       Indiana      38   Michigan_St      13
30          Iowa      25       Penn_St      24
31      Michigan      24    Washington       7
32  Northwestern      19        Purdue       0
33        Oregon      56       Rutgers      10
34          UCLA      20      Maryland      17
35       Ohio_St      34     Wisconsin       0
36       Indiana      56          UCLA       6
37          Iowa      41     Minnesota       3
38      Michigan      31   Michigan_St      20
39      Nebraska      28  Northwestern      21
40        Oregon      21     Wisconsin       7
41       Rutgers      27        Purdue      24
42    Washington      42      Illinois      25
43      Illinois      35       Rutgers      13
44       Indiana      55      Maryland      10
45      Michigan      21        Purdue      16
46     Minnesota      23   Michigan_St      20
47           USC      21      Nebraska      17
48       Ohio_St      38       Penn_St      14
49           USC      38  Northwestern      17
50        Oregon      18          Iowa      16
51       Indiana      27       Penn_St      24
52       Ohio_St      34        Purdue      10
53       Rutgers      35      Maryland      20
54      Nebraska      28          UCLA      21
55     Wisconsin      13    Washington      10

In [17]:
games

       day       date  team1  home1  score1  team2  home2  score2
0   739872 2025-09-13     11     -1      34      9      1      14
1   739872 2025-09-13     16     -1      33     13      1      17
2   739878 2025-09-19      3     -1      38     14      1      28
3   739879 2025-09-20      2      1      63      1     -1      10
4   739879 2025-09-20      5     -1      30      8      1      27
5   739879 2025-09-20     16      1      45      6     -1      31
6   739879 2025-09-20      4     -1      27     18      1      10
7   739886 2025-09-27      1      1      34     16     -1      32
8   739886 2025-09-27      2     -1      20      3      1      15
9   739886 2025-09-27      7      1      31     14     -1      28
10  739886 2025-09-27      9      1      17     15     -1      14
11  739886 2025-09-27     11     -1      30     12      1      24
12  739886 2025-09-27     10     -1      24     17      1       6
13  739893 2025-10-04     17     -1      24      4      1      20
14  739893 2025-10-04      5      1      24     18     -1      10
15  739893 2025-10-04      8      1      38      6     -1      27
16  739893 2025-10-04     10      1      42      7     -1       3
17  739893 2025-10-04      1     -1      43     13      1      27
18  739893 2025-10-04     15      1      42     12     -1      37
19  739899 2025-10-10     17      1      38     14     -1      19
20  739900 2025-10-11     10     -1      34      1      1      16
21  739900 2025-10-11      8     -1      34      4      1      31
22  739900 2025-10-11     15     -1      38      6      1      13
23  739900 2025-10-11      7      1      27     13     -1      20
24  739900 2025-10-11      2     -1      30     11      1      20
25  739900 2025-10-11      9     -1      22     12      1      21
26  739900 2025-10-11     16      1      31      5     -1      13
27  739900 2025-10-11      3     -1      37     18      1       0
28  739906 2025-10-17      7      1      24      8     -1       6
29  739907 2025-10-18      2      1      38      6     -1      13
30  739907 2025-10-18      3      1      25     12     -1      24
31  739907 2025-10-18      5      1      24     17     -1       7
32  739907 2025-10-18      9      1      19     13     -1       0
33  739907 2025-10-18     11     -1      56     14      1      10
34  739907 2025-10-18     15      1      20      4     -1      17
35  739907 2025-10-18     10     -1      34     18      1       0
36  739914 2025-10-25      2      1      56     15     -1       6
37  739914 2025-10-25      3      1      41      7     -1       3
38  739914 2025-10-25      5     -1      31      6      1      20
39  739914 2025-10-25      8      1      28      9     -1      21
40  739914 2025-10-25     11      1      21     18     -1       7
41  739914 2025-10-25     14     -1      27     13      1      24
42  739914 2025-10-25     17      1      42      1     -1      25
43  739921 2025-11-01      1      1      35     14     -1      13
44  739921 2025-11-01      2     -1      55      4      1      10
45  739921 2025-11-01      5      1      21     13     -1      16
46  739921 2025-11-01      7      1      23      6     -1      20
47  739921 2025-11-01     16     -1      21      8      1      17
48  739921 2025-11-01     10      1      38     12     -1      14
49  739927 2025-11-07     16      1      38      9     -1      17
50  739928 2025-11-08     11     -1      18      3      1      16
51  739928 2025-11-08      2     -1      27     12      1      24
52  739928 2025-11-08     10     -1      34     13      1      10
53  739928 2025-11-08     14      1      35      4     -1      20
54  739928 2025-11-08      8     -1      28     15      1      21
55  739928 2025-11-08     18      1      13     17     -1      10